export { detectFramework } from './framework-detector';
export { extractNextAppRoutes } from './next-app-router';
export { extractNextPagesRoutes } from './next-pages-router';
export { extractReactRouterRoutes } from './react-router';
export { extractAngularRoutes } from './angular';
export { extractVueRoutes } from './vue-router';
export { extractHtmlRoutes } from './html';
export { extractRemixRoutes } from './remix';
export { extractSvelteKitRoutes } from './sveltekit';
